config/routes.rb
Rails.application.routes.draw do
  resources :solar_modules do
    collection do
      get 'update_solar_modules'
    end
  end
  resources :module_ms

end

app/models/module_m.rb
class ModuleM < ActiveRecord::Base
	has_many :solar_modules
end

app/models/solar_module.rb
class SolarModule < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :module_m
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/solar_modules_controller.rb
class SolarModulesController < ApplicationController
  before_action :set_solar_module, only: [:show, :edit, :update, :destroy]

  # GET /solar_modules
  # GET /solar_modules.json
  def index
    @solar_modules = SolarModule.all
  end

  # GET /solar_modules/1
  # GET /solar_modules/1.json
  def show
  end

  # GET /solar_modules/new
  def new
    @solar_module = SolarModule.new
    @solar_m = SolarModule.where("module_m_id = '?'") 
    @module_ms = ModuleM.all
    @solar_modules = SolarModule.where(module_m_id: @module_ms[0].id)

  end

  # GET /solar_modules/1/edit
  def edit
    @solar_module = SolarModule.new(solar_module_params)
    # @solar_m = SolarModule.where("module_m_id = '?'")
    @module_ms = ModuleM.all
  end

  # POST /solar_modules
  # POST /solar_modules.json
  def create
      @solar_module = SolarModule.new(solar_module_params)
      @module_ms = ModuleM.all
      # @solar_m = SolarModule.where("module_m_id = '?'")

    respond_to do |format|
      if @solar_module.save
        format.html { redirect_to @solar_module, notice: 'Solar module was successfully created.' }
        format.json { render :show, status: :created, location: @solar_module }
      else
        format.html { render :new }
        format.json { render json: @solar_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solar_modules/1
  # PATCH/PUT /solar_modules/1.json
  def update
    @module_ms = ModuleM.all
    @solar_m = SolarModule.where("module_m_id = ?")
     respond_to do |format|
      if @solar_module.update(solar_module_params)
        format.html { redirect_to @solar_module, notice: 'Solar module was successfully updated.' }
        format.json { render :show, status: :ok, location: @solar_module }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @solar_module.errors, status: :unprocessable_entity }

      end
    end
  end

  def update_solar_modules
    @solar_modules = SolarModule.where(module_m_id: params[:solar_module][:module_m_id])
    respond_to do |format|
      format.js {}
    end

    # @solar_modules = SolarModules.where("module_m_id = ?", params[:module_m_id])
  end
  # DELETE /solar_modules/1
  # DELETE /solar_modules/1.json
  def destroy
    @solar_module.destroy
    respond_to do |format|
      format.html { redirect_to solar_modules_url, notice: 'Solar module was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  private


    # Use callbacks to share common setup or constraints between actions.
    def set_solar_module
      @solar_module = SolarModule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solar_module_params
      params.require(:solar_module).permit(:module_m_id, :part_number, :stc, :ptc, :pmax, :isc, :imp, :voc, :vmp, :height_mm, :width_mm, :height_in, :width_in, :thickness_mm, :thickness_in, :weight_kg, :weight_lbs, :tolerance_hi, :tolerance_low, :noct, :cell_type, :frame_color, :max_sys_v, :connector_type, :fire_rating, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/solar_modules_helper.rb
module SolarModulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SolarPermitRedux</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/solar_modules/_form.html.erb
<%= form_for @solar_module, :html => {:multipart => true, :class => "product_form"} do |f| %>
  <% if @solar_module.errors.any? %>
    <div id="error_explanation">
      <ul>
        <li>
          <h2><%= pluralize(@solar_module.errors.count, "error") %> prohibited this solar_module from being saved:</h2>
        </li>
      <% @solar_module.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <li>
         <h2>Edit Product Detail</h2>
         <span class="required_notification">* Denotes Required Field</span>
    </li>



    <li>
    <%= f.select :module_m_id, @module_ms.collect { |p| [ p.name, p.id ] }, {}, data: {
          remote: true,
          url: update_solar_modules_solar_modules_path }  %>
     <span class="form_hint">Proper format test</span>
    </li>

    <li>
      <div id="solar_m">
        <%= render partial: 'select', locals: { solar_modules: @solar_modules }, layout: false %>
      </div>
    <span class="form_hint">Proper format test</span>
    </li>
    f.select :solar_m, options_for_select(@solar_m.collect { |solar_m|
    [solar_m.name.titleize, solar_m.id] }, 0), {}, { id: 'solar_modules_select' 


<!--   <li>
    <%= f.label :module_m_id, "Manufacturer" %>
    <%= f.text_field :module_m_id, :type => "number" %>
    <span class="form_hint">Proper format test</span>
  
  </li>
  <li>
    <%= f.label :part_number, "Model" %>
    <%= f.text_field :part_number, :type => "text" %>
    <span class="form_hint">First select the manufacturer, then the model</span>
  
  </li> -->
  <li>
    <%= f.label :stc, "STC" %>
    <%= f.text_field :stc %>
    <span class="form_hint">Standard Test Conditions</span>
  
  </li>
  <li>
    <%= f.label :ptc, "PTC" %>
    <%= f.text_field :ptc %>
    <span class="form_hint">PV Test USA Conditions</span>
  
  </li>
  <li>
    <%= f.label :pmax %>
    <%= f.text_field :pmax %>
    <span class="form_hint">Max Power (W)</span>
  
  </li>
  <li>
    <%= f.label :isc %>
    <%= f.text_field :isc %>
    <span class="form_hint">Short Circut Current (A)</span>
  
  </li>
  <li>
    <%= f.label :imp %>
    <%= f.text_field :imp %>
    <span class="form_hint">Max Power Current (A)</span>
  
  </li>
  <li>
    <%= f.label :voc %>
    <%= f.text_field :voc %>
    <span class="form_hint">Open Circuit Voltage (V)</span>
  
  </li>
  <li>
    <%= f.label :vmp %>
    <%= f.text_field :vmp %>
    <span class="form_hint">Max Power Voltage (V)</span>
  
  </li>
  <li>
    <%= f.label :height_mm %>
    <%= f.text_field :height_mm %>
    <span class="form_hint">Module Height in Millimeters</span>
  
  </li>
  <li>
    <%= f.label :width_mm %>
    <%= f.text_field :width_mm %>
    <span class="form_hint">Module Width in Millimeters</span>
  
  </li>
  <li>
    <%= f.label :height_in %>
    <%= f.text_field :height_in %>
    <span class="form_hint">Module Height in Inches</span>
  
  </li>
  <li>
    <%= f.label :width_in %>
    <%= f.text_field :width_in %>
    <span class="form_hint">Module Width in Inches</span>
  </li>
  <li>
    <%= f.label :thickness_mm %>
    <%= f.text_field :thickness_mm %>
    <span class="form_hint">Module Thickness in Millimeters</span>
  </li>
  <li>
    <%= f.label :thickness_in %>
    <%= f.text_field :thickness_in %>
    <span class="form_hint">Module Thickness in Inches</span>
  </li>
  <li>
    <%= f.label :weight_kg %>
    <%= f.text_field :weight_kg %>
    <span class="form_hint">Module Weight in Kilograms</span>
  </li>
  <li>
    <%= f.label :weight_lbs %>
    <%= f.text_field :weight_lbs %>
    <span class="form_hint">Module Weight in Pounds</span>
  </li>
  <li>
    <%= f.label :tolerance_hi %>
    <%= f.text_field :tolerance_hi %>
    <span class="form_hint">Module Power Tolerance (+%)</span>
  </li>
  <li>
    <%= f.label :tolerance_low %>
    <%= f.text_field :tolerance_low %>
    <span class="form_hint">Module Power Tolerance (-%)</span>
  </li>
  <li>
    <%= f.label :noct, "NOCT" %>
    <%= f.text_field :noct %>
    <span class="form_hint">Nominal Operating Cell Temperature in &deg;C</span>
  </li>
  <li>
    <%= f.label :cell_type%>
    <%= f.select :cell_type, options_for_select(["choose one", "monocrystalline", "polycrystalline"]) %>
    <span class="form_hint">Module Cell Type</span>
  </li>
  <li>
    <%= f.label :frame_color %>
    <%= f.select :frame_color, options_for_select(["choose one", "silver/clear", "black"])  %>
    <span class="form_hint">Module Frame Color</span>
  </li>
  <li>
    <%= f.label :max_sys_v, "Max System Voltage" %>
    <%= f.text_field :max_sys_v %>
    <span class="form_hint">Maximum System Voltage (usually module Max V)</span>
  </li>
  <li>
    <%= f.label :connector_type %>
    <%= f.select :connector_type, options_for_select(["choose one","Tyco", "MC4", "Amphenol"]) %>
    <span class="form_hint">Proper format test</span>
  </li>
  <li>
    <%= f.label :fire_rating %>
    <%= f.select :fire_rating, options_for_select(["choose one","Class A", "Class B", "Class C"]) %>
    <span class="form_hint">Proper format test</span>
  </li>
  <li>
    <%= f.file_field :image %>
    <span class="form_hint">Proper format test</span>
  </li>
  <li>
    <%= f.submit %>
<% end %>

app/views/solar_modules/_select.html.erb
<%= select_tag :solar_module_id, options_from_collection_for_select(@solar_modules, "id", "part_number"), name: 'solar_module[id]' %>

app/views/solar_modules/_test.html.erb
<%= form_for @solar_module, :html => {:multipart => true, :class => "product_form"} do |f| %>
  <% if @solar_module.errors.any? %>
    <div id="error_explanation">
      <ul>
        <li>
          <h2><%= pluralize(@solar_module.errors.count, "error") %> prohibited this solar_module from being saved:</h2>
        </li>
      <% @solar_module.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <li>
         <h2>Testing Drop Down Boxes</h2>
         <span class="required_notification">* Denotes Required Field</span>
    </li>
  <li>
<%= f.collection_select :solar_module, :part_number, SolarModule.all, :id, :part_number %>

    <span class="form_hint">Proper format test</span>
  </li>

    <%= f.submit %>
<% end %>

app/views/solar_modules/edit.html.erb
<h1>Editing solar_module</h1>

<%= render 'form' %>

<%= link_to 'Show', @solar_module %> |
<%= link_to 'Back', solar_modules_path %>

app/views/solar_modules/index.html.erb
<div class="page_container">
  <h1>Listing Solar Modules</h1>
  <%= link_to 'New Solar module', new_solar_module_path %>        
        <!-- CSS3 Data Grids -->
        <!-- inputs for table column filtering -->
        <!-- number of inputs == number of table columns -->
  <input id="col1" name="#" type="checkbox" />
  <input id="col2" name="#" type="checkbox" />
  <input id="col3" name="#" type="checkbox" />
  <input id="col4" name="#" type="checkbox" />
  <input id="col5" name="#" type="checkbox" />
  <input id="col6" name="#" type="checkbox" />
  <input id="col7" name="#" type="checkbox" />
  <input id="col8" name="#" type="checkbox" />
  <input id="col9" name="#" type="checkbox" />
  <input id="col10" name="#" type="checkbox" />
  <input id="col11" name="#" type="checkbox" />
  <input id="col12" name="#" type="checkbox" />
  <input id="col13" name="#" type="checkbox" />
  <input id="col14" name="#" type="checkbox" />
  <input id="col15" name="#" type="checkbox" />
  <input id="col16" name="#" type="checkbox" />
  <input id="col17" name="#" type="checkbox" />
  <input id="col18" name="#" type="checkbox" />

  <table class="qlabs_grid_container">
    <!-- TABLE HEADER -->
    <thead>
    <tr class="header_row">
        <td colspan="19" class="header_cell">
            <h2 class="table_header">Solar Modules</h2> <!-- header label -->

            <!-- table column filtering panel (optional) -->
              <label for="table_config" class="table_config">Table Filter</label> <!-- button label -->
              <input id="table_config" name="#" type="checkbox" />
              <div class="table_config">
                <h3 class="table_config">Active columns</h3> <!-- panel header -->
                <ul>
                  <li><label for="col1">Image</label></li>
                  <li><label for="col2">Manufacturer</label></li>
                  <li><label for="col3">Model</label></li>
                  <li><label for="col4">STC</label></li>
                  <li><label for="col5">PTC</label></li>
                  <li><label for="col6">Pmax</label></li>
                  <li><label for="col7">Isc</label></li>
                  <li><label for="col8">Imp</label></li>
                  <li><label for="col9">Voc</label></li>
                  <li><label for="col10">Vmp</label></li>
                  <li><label for="col11">Height (in)</label></li>
                  <li><label for="col12">Width (in)</label></li>
                  <li><label for="col13">Weight (lbs)</label></li>
                  <li><label for="col14">Cell Type</label></li>
                  <li><label for="col15">Frame Color</label></li>
                  <li><label for="col16">Spec Sheets</label></li>
                  <li><label for="col17">Manuals</label></li>
                  <li><label for="col18">Warranty</label></li>
                </ul>     
              </div>
              <!-- / -->
            </td>
          </tr>
        </thead>    

        <!-- TABLE BODY -->
   <tbody class="data_container">
   
    <!-- SUBHEADER -->
    <!-- define optional columns width here -->        
    <tr class="subheader_row">
      <td class="subheader_cell">Image</td>
      <td class="subheader_cell">Manufacturer</td>
      <td class="subheader_cell">Model</td>
      <td class="subheader_cell">STC</td>
      <td class="subheader_cell">PTC</td>
      <td class="subheader_cell">Pmax</td>
      <td class="subheader_cell">Isc</td>
      <td class="subheader_cell">Imp</td>
      <td class="subheader_cell">Voc</td>
      <td class="subheader_cell">Vmp</td>
      <td class="subheader_cell">Height (in)</td>
      <td class="subheader_cell">Width (in)</td>
      <td class="subheader_cell">Weight (lbs)</td>
      <td class="subheader_cell" >Cell Type<div class="qlabs_tooltip">i<span><strong>Length</strong>This tooltip is positioned above a hovered item.</span></div></td>
      <td class="subheader_cell">Frame Color</td>
      <td class="subheader_cell">Spec Sheets</td>
      <td class="subheader_cell">Manuals</td>
      <td class="subheader_cell">Warranty</td>  
      <td colspan="3" class="subheader_cell" >Action</td>
    </tr>
  
    <% @solar_modules.each do |solar_module| %>
      <tr class="<%= cycle("data_odd", "data_even") %>">
        <td class="data_cell" ><%= link_to image_tag(solar_module.image.url(:thumb)), solar_module.image.url, :target => "_blank" %></td>
        <td class="data_cell" ><%= solar_module.module_m_id %></td>
        <td class="data_cell" ><%= solar_module.part_number %></td>
        <td class="data_cell" ><%= solar_module.stc %></td>
        <td class="data_cell" ><%= solar_module.ptc %></td>
        <td class="data_cell" ><%= solar_module.pmax %></td>
        <td class="data_cell" ><%= solar_module.isc %></td>
        <td class="data_cell" ><%= solar_module.imp %></td>
        <td class="data_cell" ><%= solar_module.voc %></td>
        <td class="data_cell" ><%= solar_module.vmp %></td>
        <td class="data_cell" ><%= solar_module.height_in %></td>
        <td class="data_cell" ><%= solar_module.width_in %></td>
        <td class="data_cell" ><%= solar_module.weight_lbs %></td>
        <td class="data_cell" ><%= solar_module.cell_type %></td>
        <td class="data_cell" ><%= solar_module.frame_color %></td>
        <td class="data_cell" >Spec Sheets</td>
        <td class="data_cell" >Manuals</td>
        <td class="data_cell" >Warranty</td>
        <td class="data_cell" ><div style="margin-left: 5px; a:hover: {color: white;}" class="grid_button"><%= link_to 'Show', solar_module %></div>
        <div style="margin-left: 5px;" class="grid_button"><%= link_to 'Edit', edit_solar_module_path(solar_module) %></div>
       <div style="margin-left: 5px;" class="grid_button"><%= link_to 'Destroy', solar_module, method: :delete, data: { confirm: 'Are you sure?' } %></div>
     </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/solar_modules/new.html.erb
<h1>New solar_module</h1>

<%= render 'form' %>

<%= link_to 'Back', solar_modules_path %>

app/views/solar_modules/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to image_tag(@solar_module.image.url(:thumb)), @solar_module.image.url, :target => "_blank" %>

<p>
  <strong>Manufacturer:</strong>
  <%= @solar_module.module_m_id %>
</p>

<p>
  <strong>Model:</strong>
  <%= @solar_module.part_number %>
</p>

<p>
  <strong>STC:</strong>
  <%= @solar_module.stc %>
</p>

<p>
  <strong>PTC:</strong>
  <%= @solar_module.ptc %>
</p>

<p>
  <strong>Pmax:</strong>
  <%= @solar_module.pmax %>
</p>

<p>
  <strong>Isc:</strong>
  <%= @solar_module.isc %>
</p>

<p>
  <strong>Imp:</strong>
  <%= @solar_module.imp %>
</p>

<p>
  <strong>Voc:</strong>
  <%= @solar_module.voc %>
</p>

<p>
  <strong>Vmp:</strong>
  <%= @solar_module.vmp %>
</p>

<p>
  <strong>Height mm:</strong>
  <%= @solar_module.height_mm %>
</p>

<p>
  <strong>Width mm:</strong>
  <%= @solar_module.width_mm %>
</p>

<p>
  <strong>Height in:</strong>
  <%= @solar_module.height_in %>
</p>

<p>
  <strong>Width in:</strong>
  <%= @solar_module.width_in %>
</p>

<p>
  <strong>Thickness mm:</strong>
  <%= @solar_module.thickness_mm %>
</p>

<p>
  <strong>Thickness in:</strong>
  <%= @solar_module.thickness_in %>
</p>

<p>
  <strong>Weight kg:</strong>
  <%= @solar_module.weight_kg %>
</p>

<p>
  <strong>Weight lbs:</strong>
  <%= @solar_module.weight_lbs %>
</p>

<p>
  <strong>Tolerance hi:</strong>
  <%= @solar_module.tolerance_hi %>
</p>

<p>
  <strong>Tolerance low:</strong>
  <%= @solar_module.tolerance_low %>
</p>

<p>
  <strong>Noct:</strong>
  <%= @solar_module.noct %>
</p>

<p>
  <strong>Cell type:</strong>
  <%= @solar_module.cell_type %>
</p>

<p>
  <strong>Frame color:</strong>
  <%= @solar_module.frame_color %>
</p>

<p>
  <strong>Max sys v:</strong>
  <%= @solar_module.max_sys_v %>
</p>

<p>
  <strong>Connector type:</strong>
  <%= @solar_module.connector_type %>
</p>

<p>
  <strong>Fire rating:</strong>
  <%= @solar_module.fire_rating %>
</p>

<%= link_to 'Edit', edit_solar_module_path(@solar_module) %> |
<%= link_to 'Back', solar_modules_path %>

app/views/solar_modules/update_solar_modules.js.erb
$('#solar_m').html("<%= escape_javascript(render partial: 'select', locals: { solar_modules: @solar_modules }, layout: false) %>");